import { ProjectItem } from "@/common/types/projects";

export const PROJECTS: ProjectItem[] = [
  {
    id: 0,
    title: "지니제과 보안 서비스 구축 및 인프라 취약점 진단",
    slug: "genie-security-infra",
    description: "지니제과 인천 지사 물류 서비스를 Kubernetes·MariaDB·nginx로 구축하고, Kali Linux로 직접 모의해킹을 수행한 뒤 발견한 취약점까지 조치한 프로젝트입니다. SQL Injection으로 전체 송장 데이터를 탈취하고 OS Command Injection으로 root 권한 리버스 쉘까지 획득하는 과정을 재현한 다음, 코드와 설정 수준에서 대응했습니다.",
    image: "/images/projects/genie-architecture.png",
    link_demo: "https://docs.google.com/presentation/d/1EMMq2dSZ-k6Ao2I_bzKqCVIy73NIxraK/edit?usp=sharing&ouid=116104757229028852554&rtpof=true&sd=true",
    link_github: undefined,
    stacks: ["Kali Linux", "Kubernetes", "MariaDB", "Vulnerability Analysis", "SQL Injection", "Web Hacking", "Network Operations"],
    content: "Kubernetes·MariaDB·nginx로 구축한 서비스를 Kali Linux로 모의해킹하고 취약점을 조치한 팀 프로젝트입니다.",
    is_show: true,
    is_featured: true,
  },
  {
    id: 1,
    title: "가상화 기반 VM 아카데미 인프라 및 보안 구축",
    slug: "multisite-hybrid-cloud-infrastructure",
    description: "KVM, Hyper-V, VMware(ESXi), Docker, Kubernetes, AWS를 활용하여 서울 본사·영등포·인천·경기 4개 거점을 VPN으로 연결한 멀티사이트 하이브리드 클라우드 인프라를 설계·구축했습니다. 온프레미스 가상화 환경과 AWS 멀티 VPC를 통합 운영하며 각 지사별 AD/DNS/DHCP, HAProxy 로드밸런싱, Auto Scaling을 구성했습니다.",
    image: "/images/projects/project2.png",
    link_demo: "https://docs.google.com/presentation/d/1gDWPScFEgBlIvnRZqyxNlaptdar_qSIp/edit?usp=sharing&ouid=116104757229028852554&rtpof=true&sd=true",
    link_github: undefined,
    stacks: ["Docker", "Kubernetes", "AWS", "Amazon Linux", "Rocky Linux", "VirtualBox", "Server Admin"],
    content: "",
    is_show: true,
    is_featured: true,
  },
  {
    id: 2,
    title: "재해복구를 위한 고가용성 인프라 구축",
    slug: "ha-infrastructure-disaster-recovery",
    description: "본사와 지사를 VPN으로 연결하고 OSPF 기반 계층적 라우팅, HSRP 게이트웨이 이중화, MySQL Master-Slave 복제를 적용하여 장애 상황에서도 서비스 연속성을 보장하는 엔터프라이즈급 고가용성 인프라를 설계·구축했습니다.",
    image: "/images/projects/ha-infrastructure.png",
    link_demo: "https://docs.google.com/presentation/d/1DyaGdw2dTsF5a47-xq5357gQAp5U2KOp/edit?usp=sharing&ouid=116104757229028852554&rtpof=true&sd=true",
    link_github: undefined,
    stacks: ["Rocky Linux", "MySQL", "Network Operations", "Server Admin", "VirtualBox"],
    content: "",
    is_show: true,
    is_featured: true,
  },
  {
    id: 3,
    title: "디자인 공유 및 커뮤니티 웹사이트",
    slug: "design-community-portfolio",
    description: "디자이너들을 위한 작품 공유 및 커뮤니티 플랫폼입니다. 포트폴리오 업로드, 좋아요, 댓글 기능과 실시간 채팅을 통한 소통이 가능합니다. Firebase를 활용한 실시간 데이터베이스와 Zustand를 통한 상태 관리로 원활한 사용자 경험을 제공합니다.",
    image: "/images/projects/design-community.jpg",
    link_demo: "https://www.asterpiece.com",
    link_github: "https://github.com/baekchu/design_site",
    stacks: ["Next.js", "TypeScript", "TailwindCSS", "Firebase", "Zustand"],
    content: "디자이너들을 위한 종합 플랫폼으로 작품 공유, 커뮤니티, 포트폴리오 기능을 통합한 웹사이트입니다.",
    is_show: true,
    is_featured: true,
  },
  {
    id: 4,
    title: "개인 포트폴리오 웹사이트",
    slug: "personal-portfolio",
    description: "개발자를 위한 현대적이고 반응형인 개인 포트폴리오 웹사이트입니다. 다크모드, 다국어 지원, 애니메이션 효과가 적용되어 있으며, 프로젝트 쇼케이스와 기술 스택을 효과적으로 보여줍니다.",
    image: "/images/projects/personal-portfolio.jpg",
    link_demo: "https://seung-portfolio.vercel.app/",
    link_github: "https://github.com/baekchu/seung_portfolio",
    stacks: ["Next.js", "TypeScript", "TailwindCSS", "Framer Motion"],
    content: "개발자의 역량과 프로젝트를 효과적으로 보여주는 포트폴리오 웹사이트입니다.",
    is_show: true,
    is_featured: true,
  },
  {
    id: 12,
    title: "스택 오버플로우(Stack Overflow)의 발생 과정",
    slug: "stack-overflow-analysis",
    description: "어셈블리 레벨에서 스택 버퍼 오버플로우가 발생하는 원리를 분석한 연구 자료입니다. MOV와 LEA 명령어의 차이, 캐리·오버플로우 플래그의 set 조건, 함수 프롤로그/에필로그(ebp·esp·SFP·RET)와 스택 프레임 구조, 실제 어셈블리 코드 디스어셈블 분석을 통해 스택 오버플로우의 메커니즘을 설명합니다.",
    image: "/images/projects/stack-overflow.png",
    link_demo: undefined,
    link_github: undefined,
    stacks: ["Vulnerability Analysis", "Web Hacking", "Server Admin"],
    content: "어셈블리 레벨에서 스택 버퍼 오버플로우의 발생 원리를 분석한 리버스 엔지니어링 학습 자료입니다.",
    is_show: true,
    is_featured: false,
  },
  {
    id: 11,
    title: "사물인터넷(IoT) 보안 취약점과 대응 방안",
    slug: "iot-security-vulnerabilities",
    description: "초연결 사회로 진입하며 급격히 확산되는 IoT 환경의 보안 취약점을 분석한 연구 보고서입니다. OWASP IoT Top 10 취약점, CoAP 프로토콜을 악용한 디바이스 해킹 시나리오, 펌웨어·공유기·감시카메라 공격 기법을 정리하고, 빅데이터(Hadoop) 기반 블랙리스트 점검을 포함한 단계별 대응 방안을 제시합니다.",
    image: "/images/projects/iot-security.png",
    link_demo: undefined,
    link_github: undefined,
    stacks: ["Vulnerability Analysis", "Web Hacking", "Network Operations"],
    content: "IoT 초연결 환경의 보안 위협과 공격 시나리오, 대응 방안을 정리한 연구 보고서입니다.",
    is_show: true,
    is_featured: false,
  },
  {
    id: 10,
    title: "블록체인 기술과 결합된 AR",
    slug: "blockchain-ar",
    description: "AR(증강현실)과 블록체인 기술을 결합하여 신뢰성과 보안을 강화하는 탈중앙화 플랫폼을 제안한 연구 자료입니다. AR 상용화를 위한 증강현실 블록체인, DID 기반 탈중앙화 신원인증, 하이브리드 토큰 모델을 제시하고, 유사 사례(스캐넷체인)와 실패 사례(스팀잇) 분석을 통해 차별점을 도출합니다.",
    image: "/images/projects/blockchain-ar.png",
    link_demo: undefined,
    link_github: undefined,
    stacks: ["Vulnerability Analysis", "Network Operations"],
    content: "AR과 블록체인을 결합한 탈중앙화 플랫폼을 제안하고 유사·실패 사례를 분석한 연구 자료입니다.",
    is_show: true,
    is_featured: false,
  },
  {
    id: 5,
    title: "이커머스 쇼핑몰",
    slug: "first-ecommerce-shop",
    description: "처음으로 개발한 전자상거래 웹사이트로, PHP와 MySQL을 활용하여 구축했습니다. 상품 관리, 장바구니, 주문 시스템, 회원 관리 등 쇼핑몰의 기본 기능들을 구현했습니다. 관리자 패널과 결제 시스템(PayPal, 신용카드)도 포함되어 있습니다.",
    image: "/images/projects/first-ecommerce.jpg",
    link_demo: "https://docs.google.com/presentation/d/1sbt_Nw5N4y3VL1-1Cjfwo7P7NnA4Wull/edit?usp=sharing&ouid=116104757229028852554&rtpof=true&sd=true",
    link_github: "https://github.com/baekchu/ecommerce",
    stacks: ["PHP", "MySQL", "HTML", "CSS", "JavaScript", "Bootstrap"],
    content: "전자상거래의 기본 개념을 학습하며 개발한 첫 번째 쇼핑몰 프로젝트입니다.",
    is_show: true,
    is_featured: false,
  },
  {
    id: 6,
    title: "학교 수강신청 앱 UI/UX 리디자인",
    slug: "course-registration-app",
    description: "기존 학교 수강신청 시스템의 복잡한 UI를 사용자 친화적으로 개선한 모바일 애플리케이션입니다. Flutter를 사용하여 크로스 플랫폼 지원과 직관적인 인터페이스를 구현했습니다. 시간표 시각화, 검색 필터링, 즐겨찾기 기능 등을 포함합니다.",
    image: "/images/projects/course-registration.jpg",
    link_demo: "https://docs.google.com/presentation/d/1she9Vmpn7zRnFRQX6CnHfAu3asLgLpiq/edit?usp=sharing&ouid=116104757229028852554&rtpof=true&sd=true",
    link_github: "https://github.com/baekchu/flutter_project",
    stacks: ["Flutter", "Dart", "Provider"],
    content: "학생들의 수강신청 경험을 개선하기 위한 모바일 앱 리디자인 프로젝트입니다.",
    is_show: true,
    is_featured: false,
  },
  {
    id: 7,
    title: "데이터베이스 백업 프로그램",
    slug: "database-backup-program",
    description: "기업용 데이터베이스의 자동 백업 및 복원을 담당하는 데스크톱 애플리케이션입니다. C#과 .NET Framework를 사용하여 개발했으며, 스케줄링, 압축, 암호화 기능을 포함합니다. 다양한 데이터베이스(MySQL, SQL Server, PostgreSQL)를 지원합니다.",
    image: "/images/projects/database-backup.jpg",
    link_demo: undefined,
    link_github: "https://github.com/baekchu/databackup",
    stacks: ["C#", ".NET Framework", "WPF", "Entity Framework", "SQL"],
    content: "기업 데이터의 안전한 백업과 복원을 위한 전문 도구입니다.",
    is_show: true,
    is_featured: false,
  },
];
